import { Card } from '../data/enums'

export const cardsSrc: Record<Card, string> = {
	[Card.S7]: '/cards/spades_7.png',
	[Card.S8]: '/cards/spades_8.png',
	[Card.S9]: '/cards/spades_9.png',
	[Card.S10]: '/cards/spades_10.png',
	[Card.SJ]: '/cards/spades_jack.png',
	[Card.SQ]: '/cards/spades_queen.png',
	[Card.SK]: '/cards/spades_king.png',
	[Card.SA]: '/cards/spades_ace.png',
	[Card.H7]: '/cards/hearts_7.png',
	[Card.H8]: '/cards/hearts_8.png',
	[Card.H9]: '/cards/hearts_9.png',
	[Card.H10]: '/cards/hearts_10.png',
	[Card.HJ]: '/cards/hearts_jack.png',
	[Card.HQ]: '/cards/hearts_queen.png',
	[Card.HK]: '/cards/hearts_king.png',
	[Card.HA]: '/cards/hearts_ace.png',
	[Card.C7]: '/cards/clubs_7.png',
	[Card.C8]: '/cards/clubs_8.png',
	[Card.C9]: '/cards/clubs_9.png',
	[Card.C10]: '/cards/clubs_10.png',
	[Card.CJ]: '/cards/clubs_jack.png',
	[Card.CQ]: '/cards/clubs_queen.png',
	[Card.CK]: '/cards/clubs_king.png',
	[Card.CA]: '/cards/clubs_ace.png',
	[Card.D7]: '/cards/diamonds_7.png',
	[Card.D8]: '/cards/diamonds_8.png',
	[Card.D9]: '/cards/diamonds_9.png',
	[Card.D10]: '/cards/diamonds_10.png',
	[Card.DJ]: '/cards/diamonds_jack.png',
	[Card.DQ]: '/cards/diamonds_queen.png',
	[Card.DK]: '/cards/diamonds_king.png',
	[Card.DA]: '/cards/diamonds_ace.png'
}
