import { Card } from '../data/enums'

export const cardsSrc: Record<Card, string> = {
	[Card.S7]: '/cards/spades_7.svg',
	[Card.S8]: '/cards/spades_8.svg',
	[Card.S9]: '/cards/spades_9.svg',
	[Card.S10]: '/cards/spades_10.svg',
	[Card.SJ]: '/cards/spades_jack.svg',
	[Card.SQ]: '/cards/spades_queen.svg',
	[Card.SK]: '/cards/spades_king.svg',
	[Card.SA]: '/cards/spades_ace.svg',
	[Card.H7]: '/cards/hearts_7.svg',
	[Card.H8]: '/cards/hearts_8.svg',
	[Card.H9]: '/cards/hearts_9.svg',
	[Card.H10]: '/cards/hearts_10.svg',
	[Card.HJ]: '/cards/hearts_jack.svg',
	[Card.HQ]: '/cards/hearts_queen.svg',
	[Card.HK]: '/cards/hearts_king.svg',
	[Card.HA]: '/cards/hearts_ace.svg',
	[Card.C7]: '/cards/clubs_7.svg',
	[Card.C8]: '/cards/clubs_8.svg',
	[Card.C9]: '/cards/clubs_9.svg',
	[Card.C10]: '/cards/clubs_10.svg',
	[Card.CJ]: '/cards/clubs_jack.svg',
	[Card.CQ]: '/cards/clubs_queen.svg',
	[Card.CK]: '/cards/clubs_king.svg',
	[Card.CA]: '/cards/clubs_ace.svg',
	[Card.D7]: '/cards/diamonds_7.svg',
	[Card.D8]: '/cards/diamonds_8.svg',
	[Card.D9]: '/cards/diamonds_9.svg',
	[Card.D10]: '/cards/diamonds_10.svg',
	[Card.DJ]: '/cards/diamonds_jack.svg',
	[Card.DQ]: '/cards/diamonds_queen.svg',
	[Card.DK]: '/cards/diamonds_king.svg',
	[Card.DA]: '/cards/diamonds_ace.svg'
}
